"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";

const emptyForm = { record_type: "BP", title: "", value: "", notes: "", record_date: new Date().toISOString().slice(0, 10) };
const formatDate = (value) => new Intl.DateTimeFormat("en", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T00:00:00`));
const nav = ["summary", "profile", "family_history", "measurements", "laboratory_results", "digestive_history", "follow_up", "timeline"];
const labels = { summary: "Doctor Summary", profile: "Patient Profile", family_history: "Family History", measurements: "Measurements", laboratory_results: "Laboratory Results", digestive_history: "Digestive History", follow_up: "Follow-up Tests", timeline: "Health Timeline" };

function AuthPanel() { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); async function submit(e) { e.preventDefault(); setBusy(true); setMessage(""); const result = await supabase.auth.signInWithPassword({ email, password }); if (result.error) setMessage(result.error.message); setBusy(false); } return <main className="vault-shell"><div className="vault-auth-card"><div className="vault-auth-brand"><span className="vault-heart">♥</span><span>Personal Health Records</span></div><p className="vault-eyebrow">Private medical record</p><h1>Sign in to Health Hub</h1><p className="vault-muted">This health record is protected and available only to an authenticated account.</p><form onSubmit={submit} className="vault-form"><label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required autoComplete="email" /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required autoComplete="current-password" /></label>{message && <p className="vault-message">{message}</p>}<button className="vault-primary" disabled={busy}>{busy ? "Signing in…" : "Login"}</button></form><a className="vault-back" href="/">← Return to business website</a></div></main>; }

function RecordCard({ record }) { const [opening, setOpening] = useState(false); async function openFile() { if (!record.file_url) return; setOpening(true); const { data } = await supabase.storage.from("health-files").createSignedUrl(record.file_url, 600); if (data?.signedUrl) window.open(data.signedUrl, "_blank", "noopener,noreferrer"); setOpening(false); } return <article className="hub-record"><div className="hub-record-top"><span className="hub-tag">{record.record_type}</span><time>{formatDate(record.record_date)}</time></div><h3>{record.title}</h3>{record.value && <strong>{record.value}</strong>}{record.notes && <p>{record.notes}</p>}{record.file_url && <button className="vault-file" onClick={openFile} disabled={opening}>{opening ? "Opening…" : "Open report ↗"}</button>}</article>; }

function Row({ item }) { return <div className="hub-row"><span>{item.test || item.measurement || item.label || item.name || "Record"}</span><strong className={/high|elevated|borderline/i.test(item.status || "") ? "hub-status-high" : ""}>{item.result || item.value || item.status || "—"}</strong><time>{item.reference || item.date || ""}</time></div>; }
function DocumentView({ section, document }) { if (!document) return <div className="hub-empty">The protected health document is not available yet.</div>; if (section === "summary") return <div className="hub-section"><p className="vault-eyebrow">Doctor Summary</p><h2>{document.summary?.patient} — Personal Health Record</h2><p className="hub-section-copy">{document.summary?.purpose}</p><div className="hub-summary-grid"><div><span>Patient</span><strong>{document.summary?.patient}</strong><small>Born {document.summary?.year_of_birth}</small></div><div><span>Height</span><strong>{document.summary?.height}</strong><small>Baseline record</small></div><div><span>Report date</span><strong>28 Mar 2026</strong><small>Rajshahi Medical College Hospital</small></div><div><span>Record source</span><strong>Protected</strong><small>Supabase health document</small></div></div><div className="hub-note">This record is organized for future clinical review. It is not a diagnosis or treatment plan.</div></div>;
  if (section === "profile") return <div className="hub-section"><p className="vault-eyebrow">Patient Profile</p><h2>Personal and baseline information</h2><div className="hub-card-grid"><article><span>Full name</span><strong>{document.summary?.patient}</strong><p>Year of birth: {document.summary?.year_of_birth}.</p></article><article><span>Height</span><strong>{document.summary?.height}</strong><p>Use consistent measurement conditions for future tracking.</p></article><article><span>Record source</span><strong>Supabase protected document</strong><p>{document.source_note}</p></article></div></div>;
  if (section === "family_history") return <div className="hub-section"><p className="vault-eyebrow">Family Medical History</p><h2>Reported hereditary risk context</h2><div className="hub-card-grid">{Object.entries(document.family_history || {}).map(([key, value]) => <article key={key}><span>{key.replace("_", " ")}</span><strong>{key === "maternal" ? "Maternal family" : key === "paternal" ? "Paternal family" : "Siblings"}</strong><p>{value}</p></article>)}</div></div>;
  if (section === "measurements") return <div className="hub-section"><p className="vault-eyebrow">Measurements</p><h2>Height, weight, BMI and glucose tracking</h2><div className="hub-table"><div className="hub-row"><span>Height</span><strong>{document.summary?.height}</strong><time>Baseline</time></div>{(document.measurements || []).map((item, i) => <Row item={item} key={i} />)}</div></div>;
  if (section === "laboratory_results") return <div className="hub-section"><p className="vault-eyebrow">Laboratory Results · 28 March 2026</p><h2>Rajshahi Medical College Hospital</h2><p className="hub-section-copy">Biochemical, complete haematology and serology results from the protected report document.</p><div className="hub-table">{(document.laboratory_results || []).map((item, i) => <Row item={item} key={i} />)}</div><div className="hub-note"><strong>Clinical follow-up:</strong> review elevated ALT, high MPV/PDW, borderline-high ESR and the complete CBC with a qualified healthcare professional. Still to be added when available: lipid profile, HbA1c, TSH, vitamin/mineral tests and vaccination records.</div></div>;
  if (section === "digestive_history") return <div className="hub-section"><p className="vault-eyebrow">Digestive History</p><h2>Reported gastrointestinal history</h2><div className="hub-card-grid"><article><span>Previous consultation</span><strong>{document.digestive_history?.consultation}</strong><p>{document.digestive_history?.finding}</p></article><article><span>H. pylori</span><strong>{document.digestive_history?.h_pylori}</strong><p>Historical record; current status should be reviewed if symptoms recur.</p></article><article><span>Reported symptoms</span><strong>{(document.digestive_history?.symptoms || []).join(" · ")}</strong><p>Possible triggers: {(document.digestive_history?.triggers || []).join(" · ")}.</p></article></div></div>;
  if (section === "follow_up") return <div className="hub-section"><p className="vault-eyebrow">Follow-up Tests and Doctor Discussion</p><h2>Items to update over time</h2><div className="hub-checklist">{(document.follow_up || []).map((item, i) => <div key={i}>□ {item}</div>)}</div><div className="hub-note">These are record-keeping prompts based on supplied information, not medical prescriptions.</div></div>;
  return null;
}

function MFASetup({ onComplete }) { const [factorId, setFactorId] = useState(""); const [secret, setSecret] = useState(""); const [code, setCode] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); useEffect(() => { (async () => { const result = await supabase.auth.mfa.enroll({ factorType: "totp" }); if (result.error) setError(result.error.message); else { setFactorId(result.data.id); setSecret(result.data.totp.secret); } })(); }, []); async function verify() { setBusy(true); setError(""); const challenge = await supabase.auth.mfa.challenge({ factorId }); if (challenge.error) setError(challenge.error.message); else { const result = await supabase.auth.mfa.verify({ factorId, challengeId: challenge.data.id, code: code.trim() }); if (result.error) setError(result.error.message); else onComplete(); } setBusy(false); } return <main className="vault-shell"><div className="vault-auth-card"><div className="vault-auth-brand"><span className="vault-heart">♥</span><span>Google Authenticator setup</span></div><p className="vault-eyebrow">Two-factor security</p><h1>Secure your Health Hub</h1><p className="vault-muted">In Google Authenticator, choose <strong>Enter setup key</strong>. Enter the account name and this private key, select Time-based, then enter the 6-digit code shown in the app.</p><div className="mfa-secret"><span>Manual setup key</span><code>{secret || "Loading setup key…"}</code></div><label className="mfa-code-label">6-digit authenticator code<input inputMode="numeric" maxLength={6} value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))} /></label>{error && <p className="vault-message">{error}</p>}<button className="vault-primary" disabled={busy || code.length !== 6 || !factorId} onClick={verify}>{busy ? "Verifying…" : "Enable two-factor security"}</button></div></main>; }
function MFAChallenge({ factor, onComplete }) { const [code, setCode] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); async function verify() { setBusy(true); setError(""); const challenge = await supabase.auth.mfa.challenge({ factorId: factor.id }); if (challenge.error) setError(challenge.error.message); else { const result = await supabase.auth.mfa.verify({ factorId: factor.id, challengeId: challenge.data.id, code: code.trim() }); if (result.error) setError(result.error.message); else onComplete(); } setBusy(false); } return <main className="vault-shell"><div className="vault-auth-card"><div className="vault-auth-brand"><span className="vault-heart">♥</span><span>Health Hub verification</span></div><p className="vault-eyebrow">Two-factor security</p><h1>Enter your authenticator code</h1><p className="vault-muted">Open Google Authenticator and enter the current 6-digit code to continue.</p><label className="mfa-code-label">6-digit authenticator code<input autoFocus inputMode="numeric" maxLength={6} value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))} /></label>{error && <p className="vault-message">{error}</p>}<button className="vault-primary" disabled={busy || code.length !== 6} onClick={verify}>{busy ? "Verifying…" : "Verify and continue"}</button><button className="vault-back" onClick={() => supabase.auth.signOut()}>Cancel and logout</button></div></main>; }

function HealthDashboard({ session }) { const [records, setRecords] = useState([]); const [mfaState, setMfaState] = useState("checking"); const [mfaFactor, setMfaFactor] = useState(null); const [document, setDocument] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [role, setRole] = useState("patient"); const [managedUserId, setManagedUserId] = useState(session.user.id); const [active, setActive] = useState("summary"); const [query, setQuery] = useState(""); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState(emptyForm); const [saving, setSaving] = useState(false); const name = session.user.user_metadata?.name || session.user.email?.split("@")[0] || "Patient";
  async function loadRecords(userId, isAdmin) { let q = supabase.from("health_records").select("id,user_id,record_type,title,value,notes,file_url,record_date,created_at"); if (!isAdmin) q = q.eq("user_id", userId); const result = await q.order("record_date", { ascending: false }).order("created_at", { ascending: false }); if (result.error) setError(result.error.message); else setRecords(result.data || []); }
  useEffect(() => { let mounted = true; (async () => { const assurance = await supabase.auth.mfa.getAuthenticatorAssuranceLevel(); const factors = await supabase.auth.mfa.listFactors(); const verified = (factors.data?.totp || []).find((factor) => factor.status === "verified"); if (!mounted) return; if (assurance.data?.currentLevel === "aal2") setMfaState("ready"); else if (verified) { setMfaFactor(verified); setMfaState("challenge"); } else setMfaState("setup"); })(); return () => { mounted = false; }; }, []);
  useEffect(() => { if (mfaState !== "ready") return undefined; let mounted = true; (async () => { const roleResult = await supabase.from("user_roles").select("role,user_id,email").eq("email", session.user.email?.toLowerCase() || "").maybeSingle(); const nextRole = roleResult.data?.role === "admin" ? "admin" : "patient"; const ownerId = nextRole === "admin" ? ((await supabase.from("user_roles").select("user_id").eq("email", "johurul.bsc@outlook.com").maybeSingle()).data?.user_id || session.user.id) : (roleResult.data?.user_id || session.user.id); const doc = await supabase.from("health_documents").select("document").eq("section", "health_hub").order("updated_at", { ascending: false }).limit(1).maybeSingle(); if (!mounted) return; setRole(nextRole); setManagedUserId(ownerId); setDocument(doc.data?.document || null); if (doc.error) setError(doc.error.message); await loadRecords(ownerId, nextRole === "admin"); setLoading(false); })(); return () => { mounted = false; }; }, [session.user.id, mfaState]);
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return records.filter((r) => !q || [r.title, r.record_type, r.value, r.notes].filter(Boolean).join(" ").toLowerCase().includes(q)); }, [records, query]);
  async function saveRecord(e) { e.preventDefault(); setSaving(true); const result = await supabase.from("health_records").insert({ ...form, user_id: managedUserId }).select("id,user_id,record_type,title,value,notes,file_url,record_date,created_at").single(); if (result.error) setError(result.error.message); else { setRecords((items) => [result.data, ...items]); setForm({ ...emptyForm, record_date: new Date().toISOString().slice(0, 10) }); setShowForm(false); } setSaving(false); }
  const timeline = <div className="hub-section"><div className="hub-list-head"><div><p className="vault-eyebrow">Health Timeline</p><h2>Authenticated records</h2></div><input placeholder="Search records…" value={query} onChange={(e) => setQuery(e.target.value)} /></div>{loading ? <p className="vault-muted">Loading records…</p> : filtered.length ? <div className="hub-records">{filtered.map((record) => <RecordCard key={record.id} record={record} />)}</div> : <div className="hub-empty">No records have been added yet.</div>}</div>;
  if (mfaState === "checking") return <main className="vault-shell"><p className="vault-muted">Checking two-factor security…</p></main>; if (mfaState === "setup") return <MFASetup onComplete={() => setMfaState("ready")} />; if (mfaState === "challenge") return <MFAChallenge factor={mfaFactor} onComplete={() => setMfaState("ready")} />;
  return <main className="hub-dashboard"><header className="hub-topbar"><a className="vault-brand" href="/"><span className="vault-heart">♥</span> Health Hub</a><div className="vault-user"><span>{name}</span><button onClick={() => supabase.auth.signOut()}>Logout</button></div></header><div className="hub-layout"><aside className="hub-sidebar"><p className="hub-sidebar-title">Health Hub</p><p className="hub-sidebar-user">Protected medical record</p><nav>{nav.map((item) => <button key={item} className={active === item ? "hub-nav-active" : ""} onClick={() => setActive(item)}>{labels[item]}</button>)}</nav></aside><div className="hub-main"><div className="hub-mobile-nav">{nav.map((item) => <button key={item} className={active === item ? "hub-nav-active" : ""} onClick={() => setActive(item)}>{labels[item]}</button>)}</div>{role === "admin" && <div className="hub-admin-bar"><span>Admin / Developer access</span><button className="vault-primary" onClick={() => setShowForm(true)}>+ Add record</button></div>}{showForm && <form className="vault-new-record" onSubmit={saveRecord}><h2>Add health record</h2><div className="vault-grid"><label>Type<input value={form.record_type} onChange={(e) => setForm({ ...form, record_type: e.target.value })} required /></label><label>Date<input type="date" value={form.record_date} onChange={(e) => setForm({ ...form, record_date: e.target.value })} required /></label><label>Title<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /></label><label>Value<input value={form.value} onChange={(e) => setForm({ ...form, value: e.target.value })} required /></label><label className="vault-wide">Notes<textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></label></div><div className="vault-actions"><button type="button" onClick={() => setShowForm(false)}>Cancel</button><button className="vault-primary" disabled={saving}>{saving ? "Saving…" : "Save record"}</button></div></form>}{error && <p className="vault-message">{error}</p>}{active === "timeline" ? timeline : <DocumentView section={active} document={document} />}</div></div></main>; }

export default function PrivateVaultPage() { const [session, setSession] = useState(undefined); useEffect(() => { supabase.auth.getSession().then(({ data }) => setSession(data.session)); const { data } = supabase.auth.onAuthStateChange((_event, next) => setSession(next)); return () => data.subscription.unsubscribe(); }, []); if (session === undefined) return <main className="vault-shell"><p className="vault-muted">Checking secure access…</p></main>; return session ? <HealthDashboard session={session} /> : <AuthPanel />; }
